echo 'hse_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=hse_grsna_abl_fo data.walk_method='node2vec'
echo 'dhfr_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=dhfr_grsna_abl_fo data.walk_method='node2vec'
echo 'imdb_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=imdb_grsna_abl_fo data.walk_method='node2vec'
echo 'p53_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=p53_grsna_abl_fo data.walk_method='node2vec'
echo 'reddit_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=reddit_grsna_abl_fo data.walk_method='node2vec'
echo 'aids_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=aids_grsna_abl_fo data.walk_method='node2vec'
echo 'proteins_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=proteins_grsna_abl_fo data.walk_method='node2vec'
echo 'mmp_grsna_abl_fo_node2vec'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=mmp_grsna_abl_fo data.walk_method='node2vec'

echo 'hse_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=hse_grsna_abl_fo data.walk_method='random_walk'
echo 'dhfr_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=dhfr_grsna_abl_fo data.walk_method='random_walk'
echo 'imdb_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=imdb_grsna_abl_fo data.walk_method='random_walk'
echo 'p53_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=p53_grsna_abl_fo data.walk_method='random_walk'
echo 'reddit_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=reddit_grsna_abl_fo data.walk_method='random_walk'
echo 'aids_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=aids_grsna_abl_fo data.walk_method='random_walk'
echo 'proteins_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=proteins_grsna_abl_fo data.walk_method='random_walk'
echo 'mmp_grsna_abl_fo_random_walk'
CUDA_VISIBLE_DEVICES=1 python src/multi_train.py experiment=mmp_grsna_abl_fo data.walk_method='random_walk'
