# random walk
echo 'hse_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=hse_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'dhfr_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=dhfr_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'imdb_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=imdb_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'p53_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=p53_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'reddit_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=reddit_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'aids_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=aids_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'proteins_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=proteins_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
echo 'mmp_grsna_abl_combined_random_walk'
CUDA_VISIBLE_DEVICES=2 python src/multi_train.py experiment=mmp_grsna_abl_fo data.walk_method='random_walk' data.ablation_mode='combined' model.structure_feat_size='14*${data.num_walks_per_node}+\(${data.walk_length}+1\)*${data.num_walks_per_node}'
